#!/usr/bin/env bash
# command to install nginx on web server

sudo apt-get update
sudo apt-get install nginx
sudo ufw "Nginx HTTP"

echo "Hello world!" | sudo tee /var/www/html/index.html

# testing nginx configurations

sudo service nginx reload
