#!/usr/bin/env bash
# parses an Apache log file and displays the IP and HTTP code for each visitor, along with the number of occurences.

file_h="apache-access.log"
awk -F' ' '{ print $1, $9}' $file_h | sort | uniq -c| sort -nr
